apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rdbox-master-00
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.179.1
    path: /usr/local/share/rdbox
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claims-scaleout-for-each-robot
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
